name: First Workflow 
#jsf
on: workflow_dispatch 
jobs: 
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print greeting 
        run: echo "Hello World"
      - name: Print name
        run: echo "Shiva" 
        
      
  
  
