name: parallel with matrix
#on which event to be triggered
on: [workflow_dispatch]

jobs:
  build_number:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies 
      run: |
          python -m pip install --upgrade pip
          pip install pytest
          
    - name : Run tests
      run: |
        python -m pytest multi1.py 
