# .github/workflows/reusable.yml
name: Reusable - Say Hello

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      test-file:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Niharika 
        run: echo "Hi Niha"
  test1:
    runs-on: ubuntu-latest   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          python -m pytest ${{ inputs.test-file }}
