# GitHub Actions Workflow - YAML Anchors & Aliases Example

name: Say Hello

on:
  push

# Common Python setup steps
python_setup: &python_config
  name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.11'

# Common dependency installation
install_deps: &install_dependencies
  name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install pytest

common_env: &shared_env
  PYTHON_VERSION: '3.11'
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      <<: *shared_env
      TEST_ENV: 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - *python_config
    - *install_dependencies
        
    - name: Run tests
      run: |
        python -m pytest add.py

  build:
    runs-on: ubuntu-latest
    env:
      <<: *shared_env
      BUILD_ENV: 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - *python_config
    - *install_dependencies
    
    - name: Build application
      run: |
        echo "Building with Python $PYTHON_VERSION"
      

  
